name: Test homebrew install
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 3 * * *"

jobs:
  live-brew-install:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ macos-10.15, macos-11.0 ]
        experimental: [true]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update brew
        run: brew update

      - name: Run brew install
        run: brew install ubuntu/microk8s/microk8s
